# java vars
JAVA_URL: "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz"
APP_HOME_DIR: /home/ubuntu
JAVA_HOME_DIR: "{{ APP_HOME_DIR }}/java"
IS_REMOTE_SRC: yes
JAVA_ZIP_FILE: "OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz"