---
 - name: Install tomcat and configure
   block: 
      - name: Creating the directory for topmcat
        file:
          dest: "{{ TOMCAT_HOME_DIR }}"
          state: directory
      - name: Download tomcat
        get_url:
           url: "{{ item }}"
           dest: "{{ APP_HOME_DIR }}"
        loop:
          - "{{ TOMCAT_URL }}"
      - name: Extracting the tomcat
        unarchive:
            src: "{{ APP_HOME_DIR }}/{{ TOMCAT_ZIP_FILE }}"
            dest: "{{ TOMCAT_HOME_DIR }}"
            remote_src: "{{ IS_REMOTE_SRC }}"
            extra_opts:
              - --strip-components=1
      - name: Adding export variables in .bash_profile
        lineinfile:
           path: ~/.bash_profile
           insertbefore: EOF
           line: "{{ item }}"
        loop:
           - '###### Created using ansible scripts ########'
           - 'export CATALINA_HOME={{ TOMCAT_HOME_DIR }}'
           - 'export PATH=${{ TOMCAT_HOME_DIR }}/bin:$PATH'

      - name: coping Config.properties file
        template:
           src: "Config.properties"
           dest: "{{ TOMCAT_HOME_DIR }}/webapps/Config.properties"
      - name: starting tomcat
        shell: |
          source ~/.bashrc
          nohup sh catalina.sh run >> ../logs/sarath.log &
        args:
         chdir: "{{ TOMCAT_HOME_DIR }}/bin"
   tags:
     - never
     - tomcat